### ISSUE TITLE
Outdated Dependency Highlighter

### ISSUE THREAD

**Issue by TheFruxz** [marcelkliemannel/intellij-gradle-utilities-plugin#22]
A feature request:

A highlighter for outdated dependencies would be nice, which you can update with a [ALT]-[ENTER] quick-fix

**Comment by marcelkliemannel** [comment]
This should already be possible with built-in IntelliJ capabilities:
<img width="813" alt="Screenshot 2022-11-28 at 21 22 33" src="https://user-images.githubusercontent.com/3964073/204373462-7fa32f1d-9028-47df-aecb-860e82c03c97.png">
(This is available through the bundled "Package Search" plugin.)
